version: '{build}'
image: Visual Studio 2015
platform:
- x86
- x64
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
  - PYTHON: 36
  - CONDA: 36
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    } elseif ($env:CONDA) {
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
    }
- if defined PYTHON (
    pip install --disable-pip-version-check --user --upgrade pip setuptools wheel pybind11
  ) else (
    conda config --set always_yes yes --set changeps1 no &&
    conda config --add channels conda-forge &&
    conda update -q conda &&
    conda install -q conda-build
  )
build_script:
- git submodule init
- git submodule update
- if defined PYTHON (
    python setup.py sdist &&
    for %%f in (dist\*.tar.gz) do (pip install --verbose %%f) &&
    python setup.py bdist_wheel
  ) else (
    conda build conda.recipe &&
    conda install --use-local pyglucose
  )
test_script:
- python tests\test_pyglucose.py
artifacts:
- path: 'dist/*.whl'
